### ISSUE TITLE
Missing information when adding inbound security rule (HTTP)

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/APL-1004-deploy-configure-azure-monitor#1]
# Module: APPL-1004
#### Step:  Add inbound security rule

Description of issue
There is some missing information in the lab. It doesn't mention what service (HTTP) to configure, when adding an inbound security rule to WS-VM1

<img width="466" alt="image" src="https://github.com/MicrosoftLearning/APL-1004-deploy-configure-azure-monitor/assets/53346841/15e47350-af94-4cf6-b2c7-6038483ffc45">

**Comment by TJGitHubUser** [comment]
Thanks, this is now merged/fixed.
