### ISSUE TITLE
Deploy and configure WS-VM1 wget error

### ISSUE THREAD

**Issue by jld8850** [MicrosoftLearning/APL-1004-deploy-configure-azure-monitor#3]
# Module: 00
#### Step: Run the following command: Wget https://raw.githubusercontent.com/Azure-Samples/html-docs-hello-world/master/index.html-OutFile index.html

Error:
PS C:\inetpub\wwwroot> Wget https://raw.githubusercontent.com/Azure-Samples/html-docs-hello-world/master/index.html-OutFile index.html
Invoke-WebRequest : A positional parameter cannot be found that accepts argument 'index.html'.
At line:1 char:1
+ Wget https://raw.githubusercontent.com/Azure-Samples/html-docs-hello- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Repro steps:

1.
1.
1.

**Comment by kboerman** [comment]
Same issue experienced with my session. Have no solution at the moment

**Comment by TJGitHubUser** [comment]
Missing space in the PowerShell syntax. Fixed now, thanks.
